name: CI
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Flutter channel stable
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Check Flutter status
        run: flutter doctor -v

      - name: Flutter get packages
        run: flutter pub get

      - name: Enable Flutter Web
        run: flutter config --enable-web

      - name: Build Flutter Web
        run: flutter build web

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: web-build
          path: build/web

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: web-build
      - name: Display structure of build files
        run: ls -R
        working-directory: ./web
      - name: Deploy to GH Pages
        run: |
          cd build/web
          git init
          # type configurations: your user.email and user.name followed lines 
          # git config --global user.email your_email 
          # git config --global user.name your_name 
          git config --global user.email ranubhardwaj89@gmail.com
          git config --global user.name himanshusharma89
          git status
          git remote add origin https://${{secrets.GH_DEPLOY}}@github.com/chunlee-thong/plov.git
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f
